### ISSUE TITLE
Its kluster not cluster stupid

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#10]
To avoid name clashes with all other types of clusters (e.g. etcd operator) I named the TPR `Kluster`. We should stick to that internally. Its not consistent at the moment, sometimes I named the variable `cluster` something `klusters`.

I don't think we should change the user facing api though.

**Comment by BugRoger** [comment]
I cleaned up part of this mess. `Cluster` has been deleted. There's still duplication in API and the KlusterSpec and SwaggerSpec.
