### ISSUE TITLE
Refactor Logging

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#100]
- [x] Remove`glog`
- [x] Insert `go-kit/log`
- [x] Formatter for `kubectl logs -f` to easy development/debugging
- [x] Leveled Logger (?!)

**Comment by databus23** [comment]
For the level logging I would suggest a simple approach for now:
For stuff thats in the "debug" area we just add a `level` key e.g.:
```
logger.Log("message", "some debug info", "level", 2)
```
We can then habe a simple filter in the `main` logger that ignores all log messages above a certain log level.
