### ISSUE TITLE
Log requestid of failed openstack calls

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#110]
We should try to log the requestid of failed calls to openstack, so that we can easily look up what went wrong in openstack.
Not sure if gophercloud can be cooreced to give us this information though.

**Comment by BugRoger** [comment]
I managed to log the `X-Openstack-Request-ID` headers.

https://github.com/sapcc/kubernikus/blob/b06c0e5b73e5816f02e37d2941bd7b71bfd0ca41/pkg/client/openstack/metadata.go#L111-L113

Not nice but works. Should be implemented in gophercloud directly. Having the request-id(s) as part of the error would be great as well.

Easy win would be to centrally add debug logging and instrumentation on the `http.Transport` of the `ProviderClient`:

https://github.com/sapcc/kubernikus/blob/b06c0e5b73e5816f02e37d2941bd7b71bfd0ca41/pkg/client/openstack/metadata.go#L32-L49

**Comment by BugRoger** [comment]
Partly implemented in #118. Need to be included at all other places where we setup a `ProviderClient`. I intent to refactor the Openstack clients...
