### ISSUE TITLE
Monitor wormhole tunnel status

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#114]
I just had to restart a wormhole client on a node for the first time to fix a node.
That got me thinking we need to monitor the tunnel status for each node because the error behaviour with a broken tunnel is mysterious and not immediately visible:
* pods can't reach the kubernetes api anymore (`EOF`)
* `kubectl` `exec`, `logs`,`proxy` does not work anymore

My current thinking is we should add a custom `NodeCondition`, maybe `TunnelUnavilable`?
We can then bubble this up via our node watcher @auhlig is working on.

**UPDATE:**
The wormhole server which runs as sidecar to the apiserver should monitor the connection state for each node and update the `NodeCondition` accordingly.

Tasks:
- [ ] Modify wormhole server library to expose connection states
- [ ] Update the wormhole controller to reconcile the `TunnelUnavailable` Condition for each node be looking up the connection status in the wormhole server for each node in the informer
- [ ] Figure out how to upgrade the wormhole server image in running Klusters (as we don't have a general upgrade feature yet). Maybe using #182

**Comment by databus23** [comment]
Digging through node problem detector, this seems to be the way to update conditions efficiently:
https://github.com/kubernetes/node-problem-detector/blob/ec470b65b045eee65d55df4ed243a801ce5953d8/pkg/problemclient/problem_client.go#L89

**Comment by auhlig** [comment]
+1 for the node-problem-detector. I did this for the kernel deadlock error once. Isn't too hard if we have a scriptable way to monitor the tunnel status

**Comment by databus23** [comment]
@auhlig I'm sorry I somehow missed that you took my mentioning of node-problem-detector that we should use it for monitoring the tunnel status. That is not what I meant. I just wanted to point out how to update a `NodeCondition` efficiently using `client-go`.
Here is my reasoning why I don't want to use npd:

1. As already mentioned in #127 using npd as a pod in the target cluster is problematic because then npd relies on the tunnel for apiserver access, which means it can't update the condition when the tunnel is unavailable.
2. I'm of the opinion that we should not "litter" the target cluster with infrastructure pods to help us do our work. The cluster belongs to the user and it should be as pristine as possible. Currently we only scheduled kube-dns in the cluster because we can't easily pull it out. We should try to not add more to the target cluster. Running node-problem-dector in the cluster should be a decision left to the user. If he wants to have it, he can install it potentially with his own custom checks for whatever.

My idea for the tunnel status node condition was that the `wormhole client` takes care of monitoring the status itself and updates the status in the apiserver using a regular kubernetes client.
It already uses the kubelets kubeconfig to [connect and authenticate](https://github.com/sapcc/kubernikus/blob/ea5e99f2afde154216b9e171ad9b42934e7d1bfe/pkg/cmd/wormhole/client.go#L74-L131) to the `wormhole server`. It can easily use that kubeconfig to setup a regular kubernetes client (same as the kubelet). That connection does not rely on the tunnel as it calls out directly to the apiserver using our SNI ingress proxy.
So the only thing the client would need to do is schedule an extra go routine that checks the tunnel availability and updates the condition when the check fails.
The tunnel can be easily checked by doing an https request to the local [tunnel endpoint](https://github.com/sapcc/kubernikus/blob/ea5e99f2afde154216b9e171ad9b42934e7d1bfe/pkg/cmd/wormhole/client.go#L58) (with sufficiently small connect and read timeouts). The health check could be also used as a watchdog that forcefully terminates the `wormhole client` when the tunnel stays unavailable for an extended period of time, so that `systemd` can take care of restarting it.

**Comment by auhlig** [comment]
Understood and agreed. NPD doesn't make sense it that scenario. I'll look into this on Monday.
