### ISSUE TITLE
Preseed RBAC RoleBindings

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#122]
Preseed an additional default RoleBinding for `kubernetes_members`

See: https://github.com/sapcc/kubernikus/blob/master/pkg/controller/ground/bootstrap.go#L61

**Comment by databus23** [comment]
What would be the desired  role for an non-admin user?
Only access to the `default` namespace?
Only `read` access to the cluster? secrets too?

**Comment by BugRoger** [comment]
Let's give them write access to the `default` namespace without the ability to create or modify roles.

 I think, there's something like `view` end `edit` roles. If instead of a `ClusterRoleBinding` a `RoleBinding` is used, it will be scoped to the namespace the `RoleBinding` is created in.

So. We need a `RoleBinding` in the `default` namespace which binds the group `os:kubernetes_members` to the role `edit`. Not sure about already existing roles. Please double check the Kubernetes documentation.

**Comment by jonathanschwarze** [comment]
eb23a17

**Comment by BugRoger** [comment]
Fixed by #136
