### ISSUE TITLE
Fix Update-Certificate Detection

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#123]
This does not seem to work:

https://github.com/sapcc/kubernikus/blob/99c42796e0fd5068bbdf9587a9d97e9e4e4d3fd9/pkg/templates/node.go#L158

The hash seems to be different from system to system:
```
lrwxrwxrwx. 1 root root     15 Dec 13 17:50 381107d7.0 -> SAPNetCA_G2.pem
```

Maybe we can go back to the `Condition=FirstBoot`? Why can't we use the inbuilt `update-ca-certificates.service`? Did this somehow run before?

**Comment by databus23** [comment]
I find it out that its different. It shouldn't be. It should be whatever comes out of `openssl x509 -noout -hash -in SAPNetCA_G2.crt` which would be `381107d7`

**Comment by BugRoger** [comment]
Maybe it's the hash of the second obsolete root certificate. I copied the value from here: https://github.wdf.sap.corp/monsoon/monsoon3/blob/master/bootcfg/ignition/master-1.7.yaml#L699

Anyway, the hash has to go :)

**Comment by SchwarzM** [comment]
```
master0 certs # openssl x509 -noout -subject_hash -in SAPGlobalRootCA.pem
48b11003
```
der hash scheint auf coreos der richtige zu sein.

**Comment by BugRoger** [comment]
Ah, ok. So the hash is from the retired Root CA. We can replace `48b11003.0` with `381107d7` until we refactor this.

**Comment by SchwarzM** [comment]
lrwxrwxrwx. 1 root root     15 Mar 24  2017 381107d7.0 -> SAPNetCA_G2.pem

GA2 ist einfach ein anderes cert.
