### ISSUE TITLE
Expose Kubernetes Version In Kluster Status

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#131]
We currently are completely opaque about the Kubernetes version. There is no way except by checking with `kubectl` which version is installed.

Add the current Kubernetes version to the Kluster Status.

**Comment by vonneudeck** [comment]
`kubectl get -o yaml kluster --all-namespaces` returns `spec.version` with something that looks like a kubernetes version. But that is just the version declared by the Helm chart. Instead of Helm, the API should return the version.
