### ISSUE TITLE
Monitor for Kubernetes Resource Limits

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#151]
In order to tune/monitor/alert the [resource limits](https://github.com/sapcc/kubernikus/blob/master/charts/kube-master/values.yaml) we need a way to compare actual usage with reserved limits.

- Collect usage metrics from Nodes 
- Collect resource allocations from Kubernetes
- Create alerts for running out of capacity
- Create alerts for nodes hitting resource limits
- Create a Grafana Dashboard to visualize the data

**Comment by vonneudeck** [comment]
Are these kubernetes internal capacities or the underlying openstack capacities?

**Comment by BugRoger** [comment]
Let's focus on Kubernetes resources first.

**Comment by BugRoger** [comment]
Done!
