### ISSUE TITLE
Reliable Availability Alert for API

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#153]
We need an outside test/alert for API availability. At the moment we are blind to total outage like:

![image](https://user-images.githubusercontent.com/147369/34764241-296cda30-f5ee-11e7-922c-42cf55bdb18c.png)

**Comment by auhlig** [comment]
Prometheus in the admin cluster could monitor the ingress pointing to the kubernikus api. https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ingress

**Comment by vonneudeck** [comment]
Also we could use the same service discovery to query a blackbox exporter outside the cluster from the prometheus within the cluster. With a bit of relabeling source and target labels we can do this with automated ingress targets.

**Comment by vonneudeck** [comment]
For that we would need of course a separate blackbox-exporter that will be queried by the internal prometheus to query then the ingress.

**Comment by auhlig** [comment]
This was done for Kubernikus in the above linked PR as seen by the blackbox exporter from within the kubernikus control plane.
We're working on cross regional monitoring using the exporter. Would also be deployed in similar fashion to baremetal clusters via our helm-charts.
Visualizing this in Grafana -especial cross regional overview- could be done using a combination of the following dashboards:
(1) https://grafana.com/plugins/raintank-worldping-app -> overview
(2) https://github.com/grafana/worldmap-panel -> overview
(3) table with details

**Comment by vonneudeck** [comment]
4. Table with cluster (columns) and blackbox exporter (rows) location. Fields coloured gradually between green and red relative to a percentage deviation from an ideal value or median over a longer time. Could simultaneously show the absolute value in ms. 
-> quick overview and some details.

5. Variant of 2. One map results per node-exporter and one per cluster.
-> geographic overview but less details than 4.

6. Map showing a coloured connection between datacentres. Unfortunately no existing plugin seems to really support this.

**Comment by BugRoger** [comment]
The internal blackbox exporters didn't catch a downtime last Saturday. The API was available but was not reachable from the outside. The internal blackbox exporters didn't catch it. 

Now that we have external blackbox probers let's add them to the monitoring setup. Make it configurable so that other's outside of our cloud can do the same.

**Comment by BugRoger** [comment]
I also think we can close this one. Looks like we probe the API with an external prober now. And we do have an alert for it.

![image](https://user-images.githubusercontent.com/147369/39009025-bfae8b32-440a-11e8-8f34-b6c51d31270d.png)

![image](https://user-images.githubusercontent.com/147369/39009061-d924c9fa-440a-11e8-95ba-410bd9b8e830.png)
