### ISSUE TITLE
Create a Build-Agent Authentication Guide

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#165]
A really common question is "How do I get the credentials to my Jenkins Job, so that it can talk to a Kubernikus Kluster".

Describe how to use `kubernikusctl` in a Build job.

- Create and uses a technical user
- Pass credentials via ENV
- Automatically renew credentials for each job

We have some prior art in our own CI pipelines.

**Comment by jonathanschwarze** [comment]
https://github.com/sapcc/kubernikus/pull/197
