### ISSUE TITLE
[Docs] Getting started

### ISSUE THREAD

**Issue by ArchiFleKs** [sapcc/kubernikus#183]
Hi, this sounds like an interesting project, but it is really hard to see how it works from your documentation, do you have more information such as a getting started ? Or an diagram of how it integrates with OpenStack, how does it compare to Magnum for example ? How do you deploy Kubernetes ? Also I don't think anyone can join your slack channel unless having an sap.com email address

**Comment by notque** [comment]
Regarding the slack channel, that makes sense and submitted a PR to remove it from the documentation. 

Regarding additional documentation, we have issues out for a improving it. It's in process, but it is helpful the specific suggestions you mentioned. A diagram of how it integrates for example.
