### ISSUE TITLE
Auto-Scaling Node Pools

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#196]
Add the option to create auto-scaling node pools. The user has to be able to specify a `min` and `max` amount of nodes the pool should scale too.

Nodes will be scaled up if there are pods that failed to schedule on any of the current nodes due to insufficient resources (CPU, Memory) as defined by resource limits on the pod. 

Scaling down is a bit more tricky we need to drain nodes before removing them. This can run into trouble with taints (pod can't be scheduled on other nodes anymore), disruption budgest, local storage,ods that cannot be moved elsewhere due to various constraints (lack of resources, non-matching node selectors or affinity, matching anti-affinity, etc)

Maybe a simple "beta" feature could be to just support scaling up without automatic scale-down. That would help with clusters that only ever are expected to grow. Like our control-planes.

Prior Art: 
- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by ironhouzi** [comment]
@BugRoger, is there a clear way to do this manually, and all the work needed is automating it? If the former, I'd love to learn about this if you have any insight to share.
