### ISSUE TITLE
Probe Customer API Servers

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#213]
Probe the availability of the customers API servers using the external Blackbox exporters.

**Comment by vonneudeck** [comment]
Add `prometheus.io/probe` annotation here for service discovery
https://github.com/sapcc/kubernikus/blob/f1735344d84e9fb71403d76ff5bab88d9a83ebb3/charts/kube-master/templates/ingress.yaml#L14-L22

Add job with three (or more) zones here
https://github.com/sapcc/kubernikus/blob/f1735344d84e9fb71403d76ff5bab88d9a83ebb3/charts/kubernikus-system/charts/prometheus/templates/_prometheus.yaml.tpl#L254

**Comment by auhlig** [comment]
No quick fix possible. I had to silence the alerts for this, as they were thrown by each and every kluster.
The [kube-master ingress](https://github.com/sapcc/kubernikus/blob/master/charts/kube-master/templates/ingress.yaml) defines 2 hosts: 1 for the API server and 1 for the wormhole. Both return different response codes in case of success.
The customer probing by @vonneudeck uses the initial prober setup, which can not handle different response codes per ingress (same module, e.g. 2xx,4xx, .. would work, but not 1 with 2xx and the other with 4xx).
Customer api probing needs fixing before the alert silence expires end of this week else please extend the silence @vonneudeck

**Comment by BugRoger** [comment]
I'd say we can close this. Customer API's are being probed now \o/
