### ISSUE TITLE
Add Alert for Clusters Stuck in Terminating

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#221]
Fire an alert when a cluster is stuck in `terminating` for a longer period of time. With current defaults the Deorbiter waits up to 24h for a cleanup.

This is bound to happen when a LB or Volume gets stuck and can't be deleted. We want to look into these incidents to figure out the core problem in Openstack.

Similar problems or bugs may arise from other controllers that implement a finaliser.  For example, a recent incident surfaced a bug in groundctl when Keystone is not responding.

**Comment by auhlig** [comment]
Currently we fire an alert if a kluster is stuck in a phase != running (so pending,creating,terminating) for more than 1h. [See alert](https://github.com/sapcc/kubernikus/blob/master/charts/kubernikus-system/charts/prometheus/kubernikus.alerts#L4-L14)

We could split to alert if kluster is in {pending,creating} for 10 min and alert if kluster is stuck in terminating for 25h or so.

**Comment by auhlig** [comment]
Done
