### ISSUE TITLE
Kubernetes Alerts for Admin Region

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#265]
We need to have the same alerting infrastructure as in other control plane regions. 

Kubelets are hanging, Bonds are failing for the `admin` region as well. With only 3 nodes the result is catastrophic. 

- Deploy `kube-monitoring`
- Hook it into Grafana/Alertmanager

**Comment by auhlig** [comment]
`kube-monitoring` was installed in admin cluster. Also wired to alertmanager and global Prometheus. However we don't have Grafana in there.

**Comment by BugRoger** [comment]
This just happened now? Or was it done before? I'm asking because the admin region had 2 nodes completely dead and I didn't see any alerts.

**Comment by auhlig** [comment]
Happend a while ago. I installed `kube-system` and `kube-monitoring` when we created the region. Only difference to other regions is the lack of OpenStack alerts.
I'll provoke an alert and check if it gets lost

**Comment by auhlig** [comment]
Blame this regex https://github.com/sapcc/helm-charts/blob/32085a9db6cc868fb8180395e242c5962058bcdc/global/prometheus-alertmanager/templates/config.yaml#L44. Region name doesn't match and admin alerts end up in #dev-null channel in slack. I'll fix

**Comment by BugRoger** [comment]
@auhlig is this done?

**Comment by auhlig** [comment]
Yes. Done. Forgot to close
