### ISSUE TITLE
Non-Openstack Authentication Strategy

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#276]
In order to authenticate against bare-metal `infra` and `control-plane` clusters, there should be an authentication strategy for the API that is not based on Keystone.

**Comment by ruvr** [comment]
I suggest to look into OpenID either directly against our AD landscape or (if not possible on AD side due to lacking Win2016 AD OpenID service) via a dex intermediate proxy on coreos?

**Comment by ruvr** [comment]
Some other interesting LDAP auth options I found:
coreos: https://github.com/coreos/bugs/issues/968
k8s: https://github.com/apprenda-kismatic/kubernetes-ldap/pull/6/files
