### ISSUE TITLE
Monitor kube-proxy health

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#284]
I fixed a cluster where all kube-proxies had to be restarted. There was no log indicating an error. So my assumption is that they got stuck on a bogus network connection.
We should try to monitor the state of kube-proxy on nodes.

`kube-proxy` has a healthcheck url `http://localhost:10249/healthz`. Unfortunately I didn't check if that was reporting an error in the concrete case before restarting the processes.

**Comment by auhlig** [comment]
Doesn't kube-proxy expose prometheus metrics on the `/healthz` endpoint?
(According to https://github.com/kubernetes/kubernetes/pull/42104)

**Comment by databus23** [comment]
Indeed.

**Comment by auhlig** [comment]
I hoped I could reuse the [previous hack](https://github.com/sapcc/kubernikus/blob/master/charts/kubernikus-system/charts/prometheus/templates/_prometheus.yaml.tpl#L237-L252). Just changing the path to `/api/v1/nodes/${1}:4194/proxy/healthz`

**Comment by databus23** [comment]
@auhlig We need to prioritise this. Looking at some of our control plane clusters we have quite a few proxies in bad shape. First thing would be to figure out if we can ingest the kube-proxy metrics and see something useful if it fails

**Comment by databus23** [comment]
Seems like the "hack" suggested by @auhlig  not going to work in our current setup, the kube-proxy endpoint is running on localhost only:
```
curl -K k-eu-nl-1.curlrc https://[REDACTED]/api/v1/nodes/k-eu-nl-1-payload-4gl6q:10249/proxy/metrics
Error: 'EOF'
Trying to reach: 'http://198.18.0.76:10249/metrics
```

**Comment by databus23** [comment]
This is still a problem we need to fix. Go away stale bot!
