### ISSUE TITLE
Prometheus Federation

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#294]
Federate the regional Kubernikus Prometheus servers to the global Prometheus.

Currently the Prometheus servers can't be federated from because the authentication is too strict. The SSL Client Certificate needs to be lifted or extended with an additional CA for which we can create our own "service" certificate.

**Comment by auhlig** [comment]
Added additional CA used by prometheus federation. Rolled out to all regions. Kubernikus Prometheis visible in global prom
