### ISSUE TITLE
Password Change Ignored

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#316]
When using `kubernikusctl` to `init` or `refresh` credentials we are asking the user for a password. Once entered the password is stored in the keychain of the OS (if available). Once the user changes his password `kubernikusctl` will try to still use the outdated password from the keychain.

Easiest would probably be to clear the password from the keychain if the login fails. Let the command throw an error and upon retry it will ask for the new password.

https://github.com/sapcc/kubernikus/blob/master/pkg/cmd/kubernikusctl/auth/refresh.go#L157-L186

**Comment by BugRoger** [comment]
@onuryilmaz Could you please take a look at this? Happy to help...

**Comment by onuryilmaz** [comment]
@BugRoger It also uses the saved password during `init` command, for instance if you change your password and `init` new projects, it will fail since it is using the password from keyring. Should we also clear during `init` command if login fails?

**Comment by BugRoger** [comment]
> Should we also clear during init command if login fails?

Yes, please. Nice catch.
