### ISSUE TITLE
Tighten Node-Pool Name Validations

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#370]
The node-pool name becomes part of the node's name. Currently we still allow underscores which leads to the following error:

```
kubelet_node_status.go:117] Unable to register node "lala-m2_xlarge-mh5gr" with API server: Node "lala-m2_xlarge-mh5gr" is invalid: metadata.name: Invalid value: "lala-m2_xlarge-mh5gr": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Tighten the validations to conform with the regex Kubernetes uses.

**Comment by databus23** [comment]
We also have problems with spaces in node names. In general we should try find out what actually is allowed as a nova and Kubernetes nodename and stick to that.

**Comment by BugRoger** [comment]
Urgs, another customer ran into this. +1

@jknipper @onuryilmaz want to pick this up?

**Comment by onuryilmaz** [comment]
I can take it

**Comment by onuryilmaz** [comment]
First findings: 

- There is a node pool name pattern: https://github.com/sapcc/kubernikus/blob/master/swagger.yml#L414
- Node pool name validation is not called at all in the generated code: https://github.com/sapcc/kubernikus/blob/master/pkg/api/models/kluster_spec.go#L104 
- Since nodePools are not validated, it is even possible to create nodePool without names from API

**Comment by onuryilmaz** [comment]
Related bug and PR: 
- https://github.com/go-swagger/go-swagger/issues/1537
- https://github.com/go-swagger/go-swagger/pull/1444

**Comment by onuryilmaz** [comment]
Node name generation is handled with Kubernetes `generator.SimpleNameGenerator`: https://github.com/sapcc/kubernikus/blob/master/pkg/controller/launch/pool_manager.go#L194

Currently, Kluster name limitation:
```
        pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
        maxLength: 20
```
With the changes in #375 pool node name limitation:
```
        pattern: '^[a-z]([a-z0-9]*)?$'
        maxLength: 20
```

Therefore, I hope it plays well with both Kubernetes and Nova :) @BugRoger @databus23
