### ISSUE TITLE
kubernikusctl in headless mode

### ISSUE THREAD

**Issue by MichaelSp** [sapcc/kubernikus#394]
Currently it's not possible to run `kubernikusctl` from within a simple `ubuntu` image:

```bash
$ kubernikusctl auth refresh
An error occurred: exec: "dbus-launch": executable file not found in $PATH
```

This is a regression introduced by https://github.com/sapcc/kubernikus/pull/270

**Comment by databus23** [comment]
Can you confirm if 
https://github.com/sapcc/kubernikus/releases/tag/v1.0.0%2B4cc8106fb5bd8859546762ba6a4bdee1d7c6597e fixes this?

It contains this change: https://github.com/sapcc/kubernikus/commit/0c614c6d34907b72ccb27fa6cd00e13741fce8cd

**Comment by dhalimi** [comment]
Hi, please ping me tomorrow, we can share a screen to resolve it

**Comment by MichaelSp** [comment]
Yes, I can confirm that it is working with the mentioned version
