### ISSUE TITLE
Fix Continuous Watch Error

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#4]
Running `groundctl` we get this error every few minutes or so:
```
W0721 10:45:47.755885   19415 reflector.go:323] github.com/sapcc/kubernikus/pkg/controller/ground/controller.go:101: watch of *v1.Kluster ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [492650215/492637872]) [492651214]
I0721 10:45:48.756031   19415 reflector.go:236] Listing and watching *v1.Kluster from github.com/sapcc/kubernikus/pkg/controller/ground/controller.go:101
```

It annoys me like hell and cludders up the otherwise nice log of groundctl.

Its not clear to me why I get this error. Seems to be its related to the client-go version because I had not seen this with operators using older versions.

**Comment by BugRoger** [comment]
Now that we are using structured logging these message have become even more annoying.The reflector is quite spammy.

Possible options to resolve this:

* Tune glog to only log ERRORs. Still garbles up the log with unstructured errors. 
* Turn glog off (to `/dev/null`). Nice log. Swallows errors.
* Write a glogkitlog adapter, that logs like glog but uses go-kit/log. Then use `gofmt` and rewrite the import during build time. Glog is a bit of a messy interface but possible.

**Comment by BugRoger** [comment]
I'm considering this issue as fixed. With the glog-shim introduced in #290 these messages are not much less annoying. They are properly tagged and can be filtered, as intended by the gods, in the tooling used for displaying structured logs.

**Comment by BugRoger** [comment]
![God](https://media.giphy.com/media/ibGFpMv1Uoais/giphy.gif)
