### ISSUE TITLE
Impossible to create cluster within the specified private subnet

### ISSUE THREAD

**Issue by kayrus** [sapcc/kubernikus#433]
There is no an ability to specify the private subnet, when private network contains multiple subnets. By default Openstack chooses the first subnet.

UPD: In addition, there is a confusion regarding `Subnet` property in Elektra dashboard and `lbSubnetID` in the API. Adding the proper `Subnet` property and fixing the Elektra caption for the `lbSubnetID` API field will make this statement clearer for end users.

**Comment by kayrus** [comment]
The only one ability to specify the subnet_id for compute instances is to create a neutron port in advance, then create an instance with the specified port ID.

**Comment by databus23** [comment]
@kayrus I think the nodes should go in same subnet as the loadbalancer? So do you think it makes sense to deploy the nodes in same subnet as the loadbalancer?
