### ISSUE TITLE
RKT Pods for Kubelet + Wormhole Client

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#44]
Stick the `kubelet` and `wormhole` into the same rkt pod.

**Comment by SchwarzM** [comment]
Sadly the information for coreos pods is scarce but I managed to find some and try it out.
It seems that what we want to achieve (tying kubelet and wormhole together) is not easily achieved.

According to the [architecture docs](https://coreos.com/rkt/docs/latest/devel/architecture.html).
A normal pod is without supervision meaning if one container dies the other one is happily running and continues to do so. Unless there is some way of supervision no one takes care about the state of the apps deployed.
Using systemd / nspawn supervision inside the pod is artificial as it could also be done with systemd outside the pod as well.

While I like the idea of using a json to define the pod, volumes and ports in a kubernetes style way I think currently it makes no sense in this case.
