### ISSUE TITLE
Bubble Up Events Log

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#47]
Attach k8s events to the Kluster TPR for important events in the cluster, e.g. Quota Exceeded while spawning nodes. Persistence are events in k8s.

Bubble up via API for display in Elektra.

**Comment by BugRoger** [comment]
See https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-controller/controller.go#L104-L107

**Comment by BugRoger** [comment]
The concern about event garbage collection is outdated. In the meantime events are being garbage collected. Default ttl is 1h as configured on the apiserver via `--event-ttl duration`. This though raises the question whether they are now stored long enough.

**Comment by BugRoger** [comment]
We need a channel to bring problems in the cluster to the users attention. 
- Quota Exceeded
- Unsupported Project Setup (e.g. no router, no private network)
- Auto-Detection of Project Parameters failed
- Node Scaling events

**Comment by databus23** [comment]
This is still in progress and can be closed once launchctl emits events.

**Comment by BugRoger** [comment]
Launchctl emits events like a big boy...
