### ISSUE TITLE
Start Smoke/Integration Test Suite

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#51]
Create a test suite for executing e2e integration tests. Ideally in Go using existing client functionality.

Initially build a smoke test that:

1. Create a Kluster via API
2. Wait for Kluster to become `ready`
3. Wait for Nodes to become `ready`
3. Fetch credentials via API
4. Schedule Pods. Wait for `ready`
5. Test Pod-to-Pod communication (maybe steal from kube-detective?)
6. Create Service. Test internal connectivity
7. Expose Service using LoadBalancer type. Test external connectivity
8. Volume creation and attachment. 
9. Delete Kluster via API. Test for successful removal of all debris.

Ideally, the suite consists of single tests instead of one big monolithic test. It should be executable from a laptop and allow to replay a part of the suite to reproduce failures locally.

**Comment by auhlig** [comment]
Initially used resty for API calls. Then generated a client based on swagger and now using that. Rebased and cleaned. Separated API and smoke tests. I'm trying to bring up a cluster before creating a PR. 
Current state is here on the [e2e branch](https://github.com/sapcc/kubernikus/tree/tests_e2e)

**Comment by auhlig** [comment]
https://github.com/sapcc/kubernikus/pull/89

**Comment by auhlig** [comment]
I think/hope we can close. Please reopen, if needed.
