### ISSUE TITLE
Create cluster button disappears after first cluster is created 

### ISSUE THREAD

**Issue by zoltan-keller** [sapcc/kubernikus#512]
On the CCloud web UI  the Kubernetes page displays a "Create Cluster" button. As soon as the first cluster is created the button disappears. It seems that it would not be possible to create more clusters, but the cli tool kubernikusctl still allows to create another cluster. The UI should behave the same way and display the Create Cluster button.

**Comment by databus23** [comment]
The button is omitted on purpose for the time being. While kubernikus supports creating more then one cluster per project we made a deliberate choice not to promote it via the dashboard.
