### ISSUE TITLE
Instance Classification

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#569]
**Is your feature request related to a problem? Please describe.**
Using the OpenStack API a list of instances is retrieved. The list includes instances created by Kubernikus as well as other VMs. That list is fed into an external system (Tennable.io) for analysis.  It should be possible to identify which instances were created by Kubernikus.

**Describe the solution you'd like**
Kubernikus should set a label on the instance.
Kubernikus should periodically check and reapply label.
Kubernikus should apply labels to already existing instances without recreating the instance. 

**Describe alternatives you've considered**
A suitable alternative would be a naming convention. e.g. a prefix for the instance name like `kubernikus--#CLUSTER--$POOL--$ID`. Though this probably requires to recreate existing instances.

**Comment by databus23** [comment]
Done and Depoyed
