### ISSUE TITLE
apiserver reachability from pods

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#57]
We are still missing some tinkering to make the apiserver available from within pods.
IIRC the pods try reach out to `https//$IP` were `$IP` is the first ip from the service CIDR which is rerouted by the kube-proxy to whatever the apiserver announces (`--advertise-address`).

One possible solution would be to have the wormhole client intercept the traffic and send it through the tunnel.

**Comment by BugRoger** [comment]
Works!! \o/
