### ISSUE TITLE
do "kubernikus auth init" support output to stdout ? 

### ISSUE THREAD

**Issue by NagleZhang** [sapcc/kubernikus#570]
Basically what we want to do is every time when we want to apply new configuration to kubernikus. 
we want using kubernikusctl to do authorization , then read the kubernetes configuration in groovy . 
then using cd plugin to do the deploy instead of sh or bash . 
because using sh or bash is hard to maintain the deploy status.

**Comment by databus23** [comment]
If you want fetch a kubeconfig for you cluster every time you can do:

`curl -H X-Auth-Token: $TOKEN https://kubernikus.$region.cloud.sap/api/v1/clusters/$clustername/credentials | jq -r .kubeconfig`

**Comment by NagleZhang** [comment]
Thanks a lot.
