### ISSUE TITLE
Switch to regional swift for rkt download in ignition

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#606]
At the moment we are using objectstore-3.eu-de-1.cloud.sap in all regions to fetch rkt components.
We should change that to use the regional swift to remove a cross cluster dependency during instance boot using a replicated swift container

@defo89 Already created a replicated container for the controlplane that we maybe can also use: https://repo.eu-de-1.cloud.sap/controlplane/flatcar-rkt/. The naming is suboptimal so, maybe we should create our own `kubernikus` container that is replicated.

We should also add a version in the request url so that we can rollout an updated version without breaking old operator installation (e.g. https://repo.eu-de-1.cloud.sap/kubernikus/rkt-v1.30.0/)

**Comment by jknipper** [comment]
Solved with https://github.com/sapcc/kubernikus/pull/662
