### ISSUE TITLE
Kubernikus Logo

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#61]
The k8s mascot sitting on a cloud and blowing septagon bubbles.

![image](https://user-images.githubusercontent.com/147369/30865798-dbe3afc8-a2d7-11e7-8f1b-837d13df65bc.png)

**Comment by BugRoger** [comment]
![logo](https://user-images.githubusercontent.com/147369/32061639-7a16e474-ba72-11e7-92fb-4715d92cf71b.png)

New logo. @edda Do you want to vectorize it?

**Comment by edda** [comment]
Yes!

**Comment by edda** [comment]
Done
