### ISSUE TITLE
Validate if imcp redirects are working

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#65]
pinging the pod cider of another nodes yields this:
```
kubernikus-m34-medium-kgn51 ~ # ping 10.180.129.1
PING 10.180.129.1 (10.180.129.1) 56(84) bytes of data.
From 10.180.0.1: icmp_seq=1 Redirect Host(New nexthop: 10.180.0.155)
64 bytes from 10.180.129.1: icmp_seq=1 ttl=64 time=1.47 ms
From 10.180.0.1: icmp_seq=2 Redirect Host(New nexthop: 10.180.0.155)
64 bytes from 10.180.129.1: icmp_seq=2 ttl=64 time=1.07 ms
From 10.180.0.1: icmp_seq=3 Redirect Host(New nexthop: 10.180.0.155)
64 bytes from 10.180.129.1: icmp_seq=3 ttl=64 time=1.15 ms
...
```

So the router sends icmp redirects.
I would expect that these redirects stop as the ping packets gets routed to the next hop directly but they don't. So it looks to me like redirects are not accepted by the node executing the ping.

Redirects are enabled and should be working:
```
kubernikus-m34-medium-kgn51 ~ # cat /proc/sys/net/ipv4/conf/ens32/accept_redirects
1
kubernikus-m34-medium-kgn51 ~ # cat /proc/sys/net/ipv4/conf/ens32/secure_redirects
1
```
I even tried disabling `secure_redirects` which didn't change anything.

I would like to have redirects working to avoid sending in-cluster communication through the router unnecessary. We should validate if it is working or make it so otherwise.

**Comment by databus23** [comment]
@SchwarzM Do we have `sysctl -w net.ipv4.conf.all.accept_redirects=1` in the ignition template by now?

**Comment by SchwarzM** [comment]
no not yet because i am unsure how to package that right if we want to update it at some point later we might need to use a daemonset or something more tangible then a systemd unit file
