### ISSUE TITLE
Deletion of Errored Klusters Fails

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#75]
In some cases Klusters can't be deleted when something goes wrong during their creation. The deletion always tries to delete the secret. If it doesn't exist it creates a deadlock.

**Comment by databus23** [comment]
Can you be more specific. IIRC the secret get created by helm and should be deleted by helm. So the only error though could happen is a bothed helm install. In that case we need to figure out how to recover from that ( I thought, `helm delete --purge` should do it)

**Comment by BugRoger** [comment]
This happens when something goes wrong before Helm even runs. The Kluster gets into `ERROR` and the termination fails, because it can't find the secret. When I saw it, it bailed with a Neutron error. I suppose, it's trying to find the router.

Can be reproduced by waiting for `putting neutron in debug mode` in #region-staging and then create a kluster 😄

**Comment by BugRoger** [comment]
Fixed, right?

**Comment by databus23** [comment]
This has been fixed a while ago.
