### ISSUE TITLE
Ingress Default Backend doesn't know JSON 

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#80]
Implement a default backend for the nginx-ingress that speaks html and json. This is required for various clients to be able to detect and report an error.

**Comment by auhlig** [comment]
This might do the trick https://github.com/kubernetes/ingress-nginx/tree/master/images/custom-error-pages. Gets the format from the request and responds accordingly.

**Comment by auhlig** [comment]
Replaced by custom backend that knows JSON and HTTP. Backend will respond accordingly. Which errors are handled by the backend has to be configured in the ingress cm. Done this for 404, 500 errors. Can we close the issue?

**Comment by databus23** [comment]
We want this in all kubernikus control planes. Has this already happend? /cc @auhlig

**Comment by auhlig** [comment]
Just admin cluster for now. I'll roll this out to the other regions today and close this issue afterwards.
