### ISSUE TITLE
Login to Nodes After Creation

### ISSUE THREAD

**Issue by SchwarzM** [sapcc/kubernikus#82]
The user has to / would like to ssh onto the newly created nodes but they have been created 
with a technical user thus have no ssh key associated.

We should ask the user for a public key or have them select on which they uploaded to openstack.

**Comment by databus23** [comment]
I think this is still very much relevant and we need a solution for it.

**Comment by BugRoger** [comment]
We have a list of available keys now: https://github.com/sapcc/kubernikus/issues/101#issuecomment-344688965

We can have the user select a key, put it in the kluster-spec and pick up the key in launchctl when spawning new nodes.

**Comment by databus23** [comment]
I’m working on it.

**Comment by BugRoger** [comment]
![image](https://user-images.githubusercontent.com/147369/34782181-30917a5c-f628-11e7-9ee5-895b9104848b.png)

**Comment by BugRoger** [comment]
Depends on #158, #157, #156
