### ISSUE TITLE
Discover all missing attributes via operator

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#85]
Right now some attributes are already filled in by the apiserver when the TPR/CRD is created: https://github.com/sapcc/kubernikus/blob/master/pkg/apis/kubernikus/factory.go#L29

This means creating a cluster manually with kubectl is pretty hard. We should have the operator/groundctl retrofit all missing attributes and have the apiserver only fill in what the user provided.

**Comment by BugRoger** [comment]
Implemented
